name: first_work
on:
  # Runs on all branches
  push: 
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Execute Single Line
        run: cat /etc/os-release
  running_script_from_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout/clone the repository in the runner GITHUB_WORKSPACE
      - name: run script
        run: chmod 755 script.sh && ./script.sh
      - name: running multiple line
        run: |
          chmod 755 script.sh
          ./script.sh
  installing_packages:
    runs-on: ubuntu-latest
    steps:
      - name: installing awscli and other artifacts
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y awscli wget 
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update -y
          sudo apt-get install -y terraform
          terraform --version >> data.txt
          aws --version >> data.txt
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: data.txt
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts in different job
        uses: actions/download-artifact@v2
        with: 
          name: artifact
          path: ./
      - name: read the artfacts file
        run: cat data.txt
    needs:
      - installing_packages
      - running_script_from_code